### ISSUE TITLE
The size of creatures can become larger or smaller.

### ISSUE THREAD

**Issue by Noogear** [Archy-X/AuraMobs#9]
Minecraft 1.20.5 introduced the scale attribute, letting you set the size of a mob.The generation of creatures of a certain level can be set to have a probability of becoming larger or smaller.
such as:
```
size:
  50:
    probability: 0.1
    scale: 0.8-1.2
  100:
    probability: 1
    scale: 1.2, 1.3
```

This means that if the creature level is between 50 and 100, there is a 10% probability of generating creatures with a scale between 0.8 and 1.2; when the creature level exceeds 100, there will be a 100% probability of generating creatures with a scale of 1.2 or 1.3.
